/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tpo4;

import javax.swing.JOptionPane;

/**
 *
 * @author Gonza
 */
public class Ejercicio4 extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio4
     */
    public Ejercicio4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLi = new javax.swing.JLabel();
        jLC = new javax.swing.JLabel();
        jLcalc = new javax.swing.JLabel();
        jLTx = new javax.swing.JLabel();
        jLT = new javax.swing.JLabel();
        jTxt = new javax.swing.JTextField();
        jB = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(236, 165, 112));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLi.setBackground(new java.awt.Color(146, 112, 47));
        jLi.setForeground(new java.awt.Color(255, 255, 255));
        jLi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pngegg.png"))); // NOI18N
        jLi.setText("jLabel1");
        jPanel1.add(jLi, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 121, -1));

        jLC.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLC.setForeground(new java.awt.Color(255, 255, 255));
        jLC.setText("C");
        jPanel1.add(jLC, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, -20, 50, 90));

        jLcalc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLcalc.setForeground(new java.awt.Color(255, 255, 51));
        jLcalc.setText("alculadora de");
        jPanel1.add(jLcalc, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jLTx.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLTx.setForeground(new java.awt.Color(255, 255, 255));
        jLTx.setText("T");
        jPanel1.add(jLTx, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        jLT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLT.setForeground(new java.awt.Color(255, 0, 51));
        jLT.setText("emperatura");
        jPanel1.add(jLT, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        jTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtActionPerformed(evt);
            }
        });
        jPanel1.add(jTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 88, -1));

        jB.setBackground(new java.awt.Color(51, 255, 255));
        jB.setForeground(new java.awt.Color(0, 0, 0));
        jB.setText("¡Medir!");
        jB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBActionPerformed(evt);
            }
        });
        jPanel1.add(jB, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 88, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/0800400000006_Eltiempoylatemperatura.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 0, 660, 210));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtActionPerformed

    private void jBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBActionPerformed
        try {
            double celsius = Double.parseDouble(jTxt.getText());
            double fahrenheit = celsius * 9/5 + 32;
            JOptionPane.showMessageDialog(this, celsius + " grados Celsius son: "+ fahrenheit + " grados fahrenheit");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingresa un numero valido");
        }
    }//GEN-LAST:event_jBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB;
    private javax.swing.JLabel jLC;
    private javax.swing.JLabel jLT;
    private javax.swing.JLabel jLTx;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLcalc;
    private javax.swing.JLabel jLi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTxt;
    // End of variables declaration//GEN-END:variables
}
